"""new fields in user model

Revision ID: 950a6820f4c6
Revises: c3db45f9706b
Create Date: 2021-09-15 22:31:28.437970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950a6820f4c6'
down_revision = 'c3db45f9706b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
